### ISSUE TITLE
Close certain issues

### ISSUE THREAD

**Issue by AnastasiaDv491** [oSoc20/urban-brussels#48]
Go over the pages and review all the issues related to them

**Comment by Yan-Shu** [comment]
Landing page : 
	- possibility to change the fun fact
	- random button
	- bug with filter/ tag (see the screen recording )
	- dashboard button not connected with the dashboard page 
	- it could be nice if the search starts when I press ’enter’
(Here my search is displayed as a filter below the search bar -> confusing)
