### ISSUE TITLE
Dashboard: Timeline + Back button

### ISSUE THREAD

**Issue by Yan-Shu** [oSoc20/urban-brussels#68]
- [x] the graph with the date is confusing (see screenshot) 
![Screen_Shot_2020-07-28_at_17](https://user-images.githubusercontent.com/63373381/88686759-b3302d80-d0f7-11ea-8c3f-d088e5285dcc.png)

- [x] it miss the button to go back to the homepage or to the map

**Comment by jbelien** [comment]
The timeline is indeed completely wrong ...

Look at this example: http://gionkunz.github.io/chartist-js/examples.html#example-timeseries-moment

**Comment by jbelien** [comment]
Not perfect, but at least the timeline is correct now.
![image](https://user-images.githubusercontent.com/1150563/88713341-6fe7b600-d11b-11ea-9ba2-d24be712b480.png)
